services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080" # HTTP port
      - "50051:50051" # gRPC port
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
      CLUSTER_HOSTNAME: "node1"

volumes:
  weaviate_data:
